### ISSUE TITLE
root end tag printed twice

### ISSUE THREAD

**Issue by LouisStrous** [mirod/xmltwig#25]
The following code prints the root end tag twice, making the output invalid XML:
```
#!/usr/bin/perl

use warnings;
use strict;

use XML::Twig;

my $t = XML::Twig->new
  (
   twig_handlers => { _default_ => sub { $_->flush; } }
  );
$t->parse('<d><title>title</title><para>p 1</para><para>p 2</para></d>');
print "\n";
```
The output was:
```
<d><title>title</title><para>p 1</para><para>p 2</para></d></d>
```
Note the double `</d>` at the end.  I ran Strawberry perl 5.22.0 on Fedora 23 in a VirtualBox virtual machine, using XML::Twig 3.49.  I also tried it using the tip commit (9e480480a6327d32ae40372b60b43c66abc83590) of the master branch of this repository on github.

**Comment by mirod** [comment]
Hi,

Try version 3.50 on xmltwig.org (sorry, not on github yet because I am away
from home and it's xmas eve ;--)

-- 
mirod

**Comment by LouisStrous** [comment]
Version 3.50 fixed the problem.  Thanks!
